In [8]:
import numpy as np

# Crear arrays
lista_python = [1, 2, 3, 4, 5]
array_numpy  = np.array([1, 2, 3, 4, 5])

print(type(lista_python))
print(type(array_numpy))
print(array_numpy)

# La diferencia clave — operaciones vectorizadas
print(f"\nLista * 2:  {[x * 2 for x in lista_python]}")  # necesita loop
print(f"Array * 2:  {array_numpy * 2}")                   # directo

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4 5]

Lista * 2:  [2, 4, 6, 8, 10]
Array * 2:  [ 2  4  6  8 10]


In [11]:
# Arrays especiales
print(np.zeros(5))           # array de ceros
print(np.ones(5))            # array de unos
print(np.arange(0, 10, 2))  # como range() pero numpy
print(np.linspace(0, 1, 5)) # 5 puntos equidistantes entre 0 y 1

# Arrays 2D — matrices
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(f"\nMatriz:\n{matriz}")
print(f"Forma: {matriz.shape}")
print(f"Dimensiones: {matriz.ndim}")
print(f"Total elementos: {matriz.size}")

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]

Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Forma: (3, 3)
Dimensiones: 2
Total elementos: 9


In [16]:
# Indexado en arrays 1D
arr = np.array([10, 20, 30, 40, 50])
print(f"Primer elemento: {arr[0]}")
print(f"Último elemento: {arr[-1]}")
print(f"Elementos 1 al 3: {arr[1:4]}")

# Indexado en matrices 2D
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(f"\nFila 0: {matriz[0]}")
print(f"Elemento fila 1, columna 2: {matriz[1, 2]}")
print(f"Toda la columna 0: {matriz[:, 0]}")
print(f"Submatriz 2x2: \n{matriz[0:2, 0:2]}")

Primer elemento: 10
Último elemento: 50
Elementos 1 al 3: [20 30 40]

Fila 0: [1 2 3]
Elemento fila 1, columna 2: 6
Toda la columna 0: [1 4 7]
Submatriz 2x2: 
[[1 2]
 [4 5]]


In [17]:
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matriz[1:, 1:])

[[5 6]
 [8 9]]


In [18]:
ventas = np.array([1200000, 850000, 2100000, 430000, 1750000, 
                   980000, 1540000, 670000, 2300000, 1100000])

# Estadísticas básicas
print(f"Total:     {np.sum(ventas):,.0f} COP")
print(f"Promedio:  {np.mean(ventas):,.0f} COP")
print(f"Mediana:   {np.median(ventas):,.0f} COP")
print(f"Máximo:    {np.max(ventas):,.0f} COP")
print(f"Mínimo:    {np.min(ventas):,.0f} COP")
print(f"Desv. std: {np.std(ventas):,.0f} COP")

# Filtrado con condiciones
ventas_altas = ventas[ventas > 1000000]
print(f"\nVentas sobre 1M: {ventas_altas}")
print(f"Cantidad: {len(ventas_altas)}")

Total:     12,920,000 COP
Promedio:  1,292,000 COP
Mediana:   1,150,000 COP
Máximo:    2,300,000 COP
Mínimo:    430,000 COP
Desv. std: 583,794 COP

Ventas sobre 1M: [1200000 2100000 1750000 1540000 2300000 1100000]
Cantidad: 6


In [26]:
np.random.seed(5)  # para que todos obtengamos los mismos resultados

# Simular temperaturas de 30 días en Valledupar (°C)
temperaturas = np.random.uniform(28, 42, 30)
temperaturas = np.round(temperaturas, 1)

print(f"Temperaturas del mes:\n{temperaturas}")
print(f"\nPromedio mensual: {np.mean(temperaturas):.1f}°C")
print(f"Día más caliente: {np.max(temperaturas):.1f}°C")
print(f"Día más fresco:   {np.min(temperaturas):.1f}°C")

# ¿Cuántos días superaron los 38°C?
dias_criticos = temperaturas[temperaturas > 38]
print(f"\nDías sobre 38°C: {len(dias_criticos)}")
print(f"Temperaturas: {dias_criticos}")

# Normalizar entre 0 y 1 (lo usarás en ML)
t_min = np.min(temperaturas)
t_max = np.max(temperaturas)
normalizadas = (temperaturas - t_min) / (t_max - t_min)
print(f"\nPrimeras 5 normalizadas: {np.round(normalizadas[:5], 3)}")

Temperaturas del mes:
[31.1 40.2 30.9 40.9 34.8 36.6 38.7 35.3 32.2 30.6 29.1 38.3 34.2 30.2
 40.3 31.8 33.8 32.1 36.8 36.1 36.4 31.7 32.  31.6 32.6 30.  30.3 41.5
 41.4 30.6]

Promedio mensual: 34.4°C
Día más caliente: 41.5°C
Día más fresco:   29.1°C

Días sobre 38°C: 7
Temperaturas: [40.2 40.9 38.7 38.3 40.3 41.5 41.4]

Primeras 5 normalizadas: [0.161 0.895 0.145 0.952 0.46 ]
